spring:
  main:
    web-application-type: none
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: org.hibernate.dialect.MySQL5InnoDBDialect


config:
  email: zainnoushad@yahoo.com
  emailName: Zain
  phone: 03322620831
  alert: false


#test: ENC(SIfgXmiE8YiwgJ3mEswxAQ==)
test: ENC(ZCQmOaZIvqCoqvJ3KqtHJ/w9Rum51tVd)


scheduler:
  enable-backup: false
connect: @con.ver@

mailjet:
  apiKey: 6029fe5c65913ed9995048b29868428d
  apiSecret: 43d336cb7207d083074a240da925ef13
